name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} Rack ${{ matrix.rack }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        rack: [ '~> 2.0', '~> 3.0' ]
        ruby: [ 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1, 3.2 ]
        gemfile: [ Gemfile ]
        exclude:
          # Rack 3 needs >= Ruby 2.4
          - { ruby: 2.2, rack: '~> 3.0' }
          - { ruby: 2.3, rack: '~> 3.0' }
    runs-on: ${{ matrix.os }}
    env:
      RACK_VERSION: ${{ matrix.rack }}
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - run: bundle exec rake
